# Generated by Django 2.1.1 on 2018-10-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180929_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
