# Generated by Django 2.1.1 on 2018-10-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181004_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
