# Generated by Django 2.1.1 on 2018-09-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='menu',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='menu',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sub_menu',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sub_menu',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
