# Generated by Django 2.1.1 on 2018-10-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20181001_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
