# Generated by Django 2.1.1 on 2018-10-02 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_page_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='menu',
            new_name='category',
        ),
    ]
