# Generated by Django 2.1.1 on 2018-10-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_auto_20181001_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyfile',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.RenameField(
            model_name='pagefile',
            old_name='image',
            new_name='file',
        ),
        migrations.AddField(
            model_name='page',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyFile',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
